stages:
  - build
  - deploy

variables:
  AWS_ACCESS_KEY_ID: AKIAZ26UVL3GACQTZYBQ
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: ap-southeast-1
  S3_BUCKET_NAME: s3://credilinq-website

build:
  stage: build
  image: node:18-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  image: 
        name: amazon/aws-cli:2.13.13
        entrypoint: [""]
  script:
    - aws --version
    - aws s3 sync build/ $S3_BUCKET_NAME/ --delete
  only:
    - development

